/*
 * Copyright WebGate Consulting AG, 2020
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * permissions and limitations under the License.
 *
 */
using System;

namespace WebGate.Dynamics.Model
{
    #pragma warning disable IDE1006 // Benennungsstile
    public class Organization
    {
        public string aciwebendpointurl { get; set; }
        public bool? allowaddressbooksyncs { get; set; }
        public bool? allowautoresponsecreation { get; set; }
        public bool? allowautounsubscribe { get; set; }
        public bool? allowautounsubscribeacknowledgement { get; set; }
        public bool? allowclientmessagebarad { get; set; }
        public bool? allowentityonlyaudit { get; set; }
        public bool? allowlegacyclientexperience { get; set; }
        public bool? allowlegacydialogsembedding { get; set; }
        public bool? allowmarketingemailexecution { get; set; }
        public bool? allowofflinescheduledsyncs { get; set; }
        public bool? allowoutlookscheduledsyncs { get; set; }
        public bool? allowunresolvedpartiesonemailsend { get; set; }
        public bool? allowuserformmodepreference { get; set; }
        public bool? allowusersseeappdownloadmessage { get; set; }
        public bool? allowwebexcelexport { get; set; }
        public string amdesignator { get; set; }
        public bool? appdesignerexperienceenabled { get; set; }
        public bool? appointmentricheditorexperience { get; set; }
        public int? auditretentionperiod { get; set; }
        public int? auditretentionperiodv2 { get; set; }
        public bool? autoapplydefaultoncasecreate { get; set; }
        public bool? autoapplydefaultoncaseupdate { get; set; }
        public bool? autoapplysla { get; set; }
        public string azureschedulerjobcollectionname { get; set; }
        public int? basecurrencyprecision { get; set; }
        public string basecurrencysymbol { get; set; }
        public string baseisocurrencycode { get; set; }
        public string bingmapsapikey { get; set; }
        public string blockedattachments { get; set; }
        public bool? bounddashboarddefaultcardexpanded { get; set; }
        public string bulkoperationprefix { get; set; }
        public string businesscardoptions { get; set; }
        public string businessclosurecalendarid { get; set; }
        public int? calendartype { get; set; }
        public string campaignprefix { get; set; }
        public bool? cascadestatusupdate { get; set; }
        public string caseprefix { get; set; }
        public string categoryprefix { get; set; }
        public string clientfeatureset { get; set; }
        public string contentsecuritypolicyconfiguration { get; set; }
        public string contractprefix { get; set; }
        public bool? cortanaproactiveexperienceenabled { get; set; }
        public DateTime? createdon { get; set; }
        public bool? createproductswithoutparentinactivestate { get; set; }
        public int? currencydecimalprecision { get; set; }
        public int? currencydisplayoption { get; set; }
        public int? currencyformatcode { get; set; }
        public string currencysymbol { get; set; }
        public int? currentbulkoperationnumber { get; set; }
        public int? currentcampaignnumber { get; set; }
        public int? currentcasenumber { get; set; }
        public int? currentcategorynumber { get; set; }
        public int? currentcontractnumber { get; set; }
        public int? currentimportsequencenumber { get; set; }
        public int? currentinvoicenumber { get; set; }
        public int? currentkanumber { get; set; }
        public int? currentkbnumber { get; set; }
        public int? currentordernumber { get; set; }
        public int? currentparsedtablenumber { get; set; }
        public int? currentquotenumber { get; set; }
        public int? dateformatcode { get; set; }
        public string dateformatstring { get; set; }
        public string dateseparator { get; set; }
        public int? dayssincerecordlastmodifiedmaxvalue { get; set; }
        public string decimalsymbol { get; set; }
        public string defaultcountrycode { get; set; }
        public string defaultcrmcustomname { get; set; }
        public string defaultemailsettings { get; set; }
        public int? defaultrecurrenceendrangetype { get; set; }
        public string defaultthemedata { get; set; }
        public string delegatedadminuserid { get; set; }
        public string disabledreason { get; set; }
        public bool? disablesocialcare { get; set; }
        public int? discountcalculationmethod { get; set; }
        public bool? displaynavigationtour { get; set; }
        public int? emailconnectionchannel { get; set; }
        public bool? emailcorrelationenabled { get; set; }
        public int? emailsendpollingperiod { get; set; }
        public bool? enablebingmapsintegration { get; set; }
        public bool? enableimmersiveskypeintegration { get; set; }
        public bool? enablelivepersonacarduci { get; set; }
        public bool? enablelivepersoncardintegrationinoffice { get; set; }
        public bool? enablelpauthoring { get; set; }
        public bool? enablemicrosoftflowintegration { get; set; }
        public bool? enablepricingoncreate { get; set; }
        public bool? enablesmartmatching { get; set; }
        public bool? enableunifiedinterfaceshellrefresh { get; set; }
        public bool? enforcereadonlyplugins { get; set; }
        public int? expirechangetrackingindays { get; set; }
        public int? expiresubscriptionsindays { get; set; }
        public string externalbaseurl { get; set; }
        public string externalpartycorrelationkeys { get; set; }
        public string externalpartyentitysettings { get; set; }
        public string featureset { get; set; }
        public DateTime? fiscalcalendarstart { get; set; }
        public string fiscalperiodformat { get; set; }
        public int? fiscalperiodformatperiod { get; set; }
        public int? fiscalperiodtype { get; set; }
        public bool? fiscalsettingsupdated { get; set; }
        public int? fiscalyeardisplaycode { get; set; }
        public string fiscalyearformat { get; set; }
        public int? fiscalyearformatprefix { get; set; }
        public int? fiscalyearformatsuffix { get; set; }
        public int? fiscalyearformatyear { get; set; }
        public string fiscalyearperiodconnect { get; set; }
        public int? fullnameconventioncode { get; set; }
        public int? futureexpansionwindow { get; set; }
        public bool? generatealertsforerrors { get; set; }
        public bool? generatealertsforinformation { get; set; }
        public bool? generatealertsforwarnings { get; set; }
        public bool? getstartedpanecontentenabled { get; set; }
        public bool? globalappendurlparametersenabled { get; set; }
        public string globalhelpurl { get; set; }
        public bool? globalhelpurlenabled { get; set; }
        public int? goalrollupexpirytime { get; set; }
        public int? goalrollupfrequency { get; set; }
        public bool? grantaccesstonetworkservice { get; set; }
        public int? hashdeltasubjectcount { get; set; }
        public string hashfilterkeywords { get; set; }
        public int? hashmaxcount { get; set; }
        public int? hashminaddresscount { get; set; }
        public string highcontrastthemedata { get; set; }
        public bool? ignoreinternalemail { get; set; }
        public bool? inactivitytimeoutenabled { get; set; }
        public int? inactivitytimeoutinmins { get; set; }
        public int? inactivitytimeoutreminderinmins { get; set; }
        public int? incomingemailexchangeemailretrievalbatchsize { get; set; }
        public string initialversion { get; set; }
        public string integrationuserid { get; set; }
        public string invoiceprefix { get; set; }
        public bool? isactioncardenabled { get; set; }
        public bool? isactionsupportfeatureenabled { get; set; }
        public bool? isactivityanalysisenabled { get; set; }
        public bool? isallmoneydecimal { get; set; }
        public bool? isappmode { get; set; }
        public bool? isappointmentattachmentsyncenabled { get; set; }
        public bool? isassignedtaskssyncenabled { get; set; }
        public bool? isauditenabled { get; set; }
        public bool? isautodatacaptureenabled { get; set; }
        public bool? isautodatacapturev2enabled { get; set; }
        public bool? isautosaveenabled { get; set; }
        public bool? isbpfentitycustomizationfeatureenabled { get; set; }
        public bool? isconflictdetectionenabledformobileclient { get; set; }
        public bool? iscontactmailingaddresssyncenabled { get; set; }
        public bool? iscontentsecuritypolicyenabled { get; set; }
        public bool? iscontextualemailenabled { get; set; }
        public bool? iscontextualhelpenabled { get; set; }
        public bool? iscustomcontrolsincanvasappsenabled { get; set; }
        public bool? isdefaultcountrycodecheckenabled { get; set; }
        public bool? isdelegateaccessenabled { get; set; }
        public bool? isdelveactionhubintegrationenabled { get; set; }
        public bool? isdisabled { get; set; }
        public bool? isduplicatedetectionenabled { get; set; }
        public bool? isduplicatedetectionenabledforimport { get; set; }
        public bool? isduplicatedetectionenabledforofflinesync { get; set; }
        public bool? isduplicatedetectionenabledforonlinecreateupdate { get; set; }
        public bool? isemailmonitoringallowed { get; set; }
        public bool? isemailserverprofilecontentfilteringenabled { get; set; }
        public bool? isenabledforallroles { get; set; }
        public bool? isexternalfilestorageenabled { get; set; }
        public bool? isexternalsearchindexenabled { get; set; }
        public bool? isfiscalperiodmonthbased { get; set; }
        public bool? isfolderautocreatedonsp { get; set; }
        public bool? isfolderbasedtrackingenabled { get; set; }
        public bool? isfulltextsearchenabled { get; set; }
        public bool? isgeospatialazuremapsintegrationenabled { get; set; }
        public bool? ishierarchicalsecuritymodelenabled { get; set; }
        public bool? isluisenabledford365bot { get; set; }
        public bool? ismailboxforcedunlockingenabled { get; set; }
        public bool? ismailboxinactivebackoffenabled { get; set; }
        public bool? ismanualsalesforecastingenabled { get; set; }
        public bool? ismobileclientondemandsyncenabled { get; set; }
        public bool? ismobileofflineenabled { get; set; }
        public bool? ismodeldrivenappsinmsteamsenabled { get; set; }
        public bool? ismsteamscollaborationenabled { get; set; }
        public bool? ismsteamsenabled { get; set; }
        public bool? ismsteamssettingchangedbyuser { get; set; }
        public bool? ismsteamsusersyncenabled { get; set; }
        public bool? isnewaddproductexperienceenabled { get; set; }
        public bool? isnotesanalysisenabled { get; set; }
        public bool? isofficegraphenabled { get; set; }
        public bool? isonedriveenabled { get; set; }
        public bool? ispaienabled { get; set; }
        public string ispdfgenerationenabled { get; set; }
        public bool? isplaybookenabled { get; set; }
        public bool? ispresenceenabled { get; set; }
        public bool? ispreviewenabledforactioncard { get; set; }
        public bool? ispreviewforautocaptureenabled { get; set; }
        public bool? ispreviewforemailmonitoringallowed { get; set; }
        public bool? ispricelistmandatory { get; set; }
        public bool? isquickcreateenabledforopportunityclose { get; set; }
        public bool? isreadauditenabled { get; set; }
        public bool? isrelationshipinsightsenabled { get; set; }
        public bool? isresourcebookingexchangesyncenabled { get; set; }
        public bool? isrichtextnotesenabled { get; set; }
        public bool? issalesassistantenabled { get; set; }
        public bool? issopintegrationenabled { get; set; }
        public bool? istextwrapenabled { get; set; }
        public bool? isuseraccessauditenabled { get; set; }
        public int? isvintegrationcode { get; set; }
        public bool? iswriteinproductsallowed { get; set; }
        public string kaprefix { get; set; }
        public string kbprefix { get; set; }
        public string kmsettings { get; set; }
        public string languagecode { get; set; }
        public string localeid { get; set; }
        public int? longdateformatcode { get; set; }
        public int? mailboxintermittentissueminrange { get; set; }
        public int? mailboxpermanentissueminrange { get; set; }
        public int? maxactionstepsinbpf { get; set; }
        public int? maxappointmentdurationdays { get; set; }
        public int? maxconditionsformobileofflinefilters { get; set; }
        public int? maxdepthforhierarchicalsecuritymodel { get; set; }
        public int? maxfolderbasedtrackingmappings { get; set; }
        public int? MaximumActiveBusinessProcessFlowsAllowed { get; set; }
        public int? maximumdynamicpropertiesallowed { get; set; }
        public int? maximumentitieswithactivesla { get; set; }
        public int? maximumslakpiperentitywithactivesla { get; set; }
        public int? maximumtrackingnumber { get; set; }
        public int? maxproductsinbundle { get; set; }
        public int? maxrecordsforexporttoexcel { get; set; }
        public int? maxrecordsforlookupfilters { get; set; }
        public int? maxslaitemspersla { get; set; }
        public int? maxsupportedinternetexplorerversion { get; set; }
        public int? maxuploadfilesize { get; set; }
        public int? maxverboseloggingmailbox { get; set; }
        public int? maxverboseloggingsynccycles { get; set; }
        public DateTime? metadatasynclasttimeofneverexpireddeletedobjects { get; set; }
        public long? metadatasynctimestamp { get; set; }
        public string microsoftflowenvironment { get; set; }
        public int? minaddressbooksyncinterval { get; set; }
        public int? minofflinesyncinterval { get; set; }
        public int? minoutlooksyncinterval { get; set; }
        public int? mobileofflineminlicenseprod { get; set; }
        public int? mobileofflineminlicensetrial { get; set; }
        public int? mobileofflinesyncinterval { get; set; }
        public DateTime? modifiedon { get; set; }
        public string name { get; set; }
        public int? negativecurrencyformatcode { get; set; }
        public int? negativeformatcode { get; set; }
        public int? nextcustomobjecttypecode { get; set; }
        public int? nexttrackingnumber { get; set; }
        public bool? notifymailboxownerofemailserverlevelalerts { get; set; }
        public string numberformat { get; set; }
        public string numbergroupformat { get; set; }
        public string numberseparator { get; set; }
        public bool? officeappsautodeploymentenabled { get; set; }
        public string officegraphdelveurl { get; set; }
        public bool? oobpricecalculationenabled { get; set; }
        public string orderprefix { get; set; }
        public string organizationid { get; set; }
        public int? organizationstate { get; set; }
        public string orgdborgsettings { get; set; }
        public bool? orginsightsenabled { get; set; }
        public bool? paipreviewscenarioenabled { get; set; }
        public string parsedtablecolumnprefix { get; set; }
        public string parsedtableprefix { get; set; }
        public int? pastexpansionwindow { get; set; }
        public string picture { get; set; }
        public string pinpointlanguagecode { get; set; }
        public int? plugintracelogsetting { get; set; }
        public string pmdesignator { get; set; }
        public string postmessagewhitelistdomains { get; set; }
        public bool? powerbifeatureenabled { get; set; }
        public int? pricingdecimalprecision { get; set; }
        public string privacystatementurl { get; set; }
        public string privilegeusergroupid { get; set; }
        public string privreportinggroupid { get; set; }
        public string privreportinggroupname { get; set; }
        public bool? productrecommendationsenabled { get; set; }
        public string qualifyleadadditionaloptions { get; set; }
        public bool? quickfindrecordlimitenabled { get; set; }
        public string quoteprefix { get; set; }
        public int? recurrencedefaultnumberofoccurrences { get; set; }
        public int? recurrenceexpansionjobbatchinterval { get; set; }
        public int? recurrenceexpansionjobbatchsize { get; set; }
        public int? recurrenceexpansionsynchcreatemax { get; set; }
        public string referencesitemapxml { get; set; }
        public string rendersecureiframeforemail { get; set; }
        public string reportinggroupid { get; set; }
        public string reportinggroupname { get; set; }
        public int? reportscripterrors { get; set; }
        public bool? requireapprovalforqueueemail { get; set; }
        public bool? requireapprovalforuseremail { get; set; }
        public bool? resolvesimilarunresolvedemailaddress { get; set; }
        public bool? restrictstatusupdate { get; set; }
        public int? rierrorstatus { get; set; }
        public string sampledataimportid { get; set; }
        public int? schedulingengine { get; set; }
        public string schemanameprefix { get; set; }
        public bool? sendbulkemailinuci { get; set; }
        public bool? servestaticresourcesfromazurecdn { get; set; }
        public bool? sessiontimeoutenabled { get; set; }
        public int? sessiontimeoutinmins { get; set; }
        public int? sessiontimeoutreminderinmins { get; set; }
        public int? sharepointdeploymenttype { get; set; }
        public bool? sharetopreviousowneronassign { get; set; }
        public bool? showkbarticledeprecationnotification { get; set; }
        public bool? showweeknumber { get; set; }
        public string signupoutlookdownloadfwlink { get; set; }
        public string sitemapxml { get; set; }
        public string slapausestates { get; set; }
        public bool? socialinsightsenabled { get; set; }
        public string socialinsightsinstance { get; set; }
        public bool? socialinsightstermsaccepted { get; set; }
        public int? sortid { get; set; }
        public string sqlaccessgroupid { get; set; }
        public string sqlaccessgroupname { get; set; }
        public bool? sqmenabled { get; set; }
        public string supportuserid { get; set; }
        public bool? suppresssla { get; set; }
        public int? syncbulkoperationbatchsize { get; set; }
        public int? syncbulkoperationmaxlimit { get; set; }
        public bool? syncoptinselection { get; set; }
        public int? syncoptinselectionstatus { get; set; }
        public string systemuserid { get; set; }
        public int? tagmaxaggressivecycles { get; set; }
        public int? tagpollingperiod { get; set; }
        public bool? taskbasedflowenabled { get; set; }
        public bool? textanalyticsenabled { get; set; }
        public int? timeformatcode { get; set; }
        public string timeformatstring { get; set; }
        public string timeseparator { get; set; }
        public int? timezoneruleversionnumber { get; set; }
        public int? tokenexpiry { get; set; }
        public string tokenkey { get; set; }
        public int? tracelogmaximumageindays { get; set; }
        public string trackingprefix { get; set; }
        public int? trackingtokenidbase { get; set; }
        public int? trackingtokeniddigits { get; set; }
        public int? uniquespecifierlength { get; set; }
        public bool? unresolveemailaddressifmultiplematch { get; set; }
        public bool? useinbuiltrulefordefaultpricelistselection { get; set; }
        public bool? uselegacyrendering { get; set; }
        public bool? usepositionhierarchy { get; set; }
        public bool? usequickfindviewforgridsearch { get; set; }
        public int? useraccessauditinginterval { get; set; }
        public bool? usereadform { get; set; }
        public string usergroupid { get; set; }
        public bool? useskypeprotocol { get; set; }
        public int? utcconversiontimezonecode { get; set; }
        public string v3calloutconfighash { get; set; }
        public long? versionnumber { get; set; }
        public string webresourcehash { get; set; }
        public int? weekstartdaycode { get; set; }
        public string widgetproperties { get; set; }
        public int? yammergroupid { get; set; }
        public string yammernetworkpermalink { get; set; }
        public bool? yammeroauthaccesstokenexpired { get; set; }
        public int? yammerpostmethod { get; set; }
        public int? yearstartweekcode { get; set; }
    }
}
